### ISSUE TITLE
WinRT component not found

### ISSUE THREAD

**Issue by wocard2** [microsoft/RegFree_WinRT#2]
I built both the WinRT component and the C# sample. Clicking on the button causes this exception:

>   System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
>   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)

I'm on Windows build 18362.239.

**Comment by manodasanW** [comment]
Are you still able to repro this?  If you are, can you confirm whether you see the forwarders (i.e. vccorlib140_app.dll, vcomp140d_app.dll, etc.) in the bin folder of the WinForms app.

**Comment by manodasanW** [comment]
Please reactivate if you are able to repro it.
